import os
from pymongo import MongoClient
from dotenv import load_dotenv

# Load configuration parameters from the environment/dotenv file
load_dotenv()

MONGO_URI = os.environ.get("MONGO_URI", "mongodb://localhost:27017/")
MONGO_DB_NAME = os.environ.get("MONGO_DB_NAME", "trailguard")

# Complete list of 20 curated Kenyan hiking trails with expanded details and high-resolution Unsplash photos
trails_data = [
    # --- Original 8 ---
    {
        "name": "Ngong Hills",
        "difficulty": "moderate",
        "distance_km": 12.0,
        "elevation_m": 2460,
        "location": "Kajiado County, near Nairobi",
        "waterfall_safety_status": "No waterfalls on this route",
        "swimming_warning": False,
        "description": "A popular hiking trail across seven hills with views of Nairobi and the Great Rift Valley.",
        "image_url": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&q=80",
        "duration_hours": 4.5,
        "gear_needed": ["Hiking boots", "Water (minimum 2L)", "Sun hat", "Windbreaker", "Sunscreen"],
        "best_season": "January to March, July to October",
        "guide_required": False,
        "starting_point": "Ngong Town Police Station Gate",
        "permit_required": True,
        "fitness_level": "intermediate"
    },
    {
        "name": "Mt. Longonot",
        "difficulty": "hard",
        "distance_km": 13.5,
        "elevation_m": 2776,
        "location": "Nakuru County, near Naivasha",
        "waterfall_safety_status": "Dry crater, no waterfalls",
        "swimming_warning": False,
        "description": "A dormant stratovolcano with a scenic crater rim walk.",
        "image_url": "https://images.unsplash.com/photo-1482862549707-f63cb32c5fd9?w=1200&q=80",
        "duration_hours": 4.5,
        "gear_needed": ["Hiking boots", "Water (minimum 3L)", "Sun hat", "Sunglasses", "High-energy snacks"],
        "best_season": "January to March, July to October",
        "guide_required": False,
        "starting_point": "KWS Longonot Main Gate",
        "permit_required": True,
        "fitness_level": "intermediate"
    },
    {
        "name": "Mt. Kenya",
        "difficulty": "hard",
        "distance_km": 52.0,
        "elevation_m": 4985,
        "location": "Central Kenya",
        "waterfall_safety_status": "Waterfalls on Chogoria route, check levels in rainy season",
        "swimming_warning": False,
        "description": "Kenya's highest mountain and Africa's second-highest, an alpine trekking experience.",
        "image_url": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80",
        "duration_hours": 32.0,
        "gear_needed": ["Warm thermal layers", "Sleeping bag", "Waterproof jacket & pants", "Trekking poles", "Headlamp"],
        "best_season": "December to March, July to September",
        "guide_required": True,
        "starting_point": "Sirimon Gate / Chogoria Gate",
        "permit_required": True,
        "fitness_level": "advanced"
    },
    {
        "name": "Kereita Forest",
        "difficulty": "moderate",
        "distance_km": 9.0,
        "elevation_m": 2200,
        "location": "Kiambu County",
        "waterfall_safety_status": "Waterfall trail can be slippery, high flow in rainy season",
        "swimming_warning": True,
        "description": "Zip-lining, forest hikes, archery, and a waterfall.",
        "image_url": "https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&q=80",
        "duration_hours": 3.0,
        "gear_needed": ["Hiking boots or running shoes", "Raincoat", "Insect repellent", "Water (1.5L)"],
        "best_season": "June to October",
        "guide_required": False,
        "starting_point": "The Forest Adventure Center",
        "permit_required": True,
        "fitness_level": "beginner"
    },
    {
        "name": "Karura Forest",
        "difficulty": "easy",
        "distance_km": 10.0,
        "elevation_m": 1680,
        "location": "Nairobi County",
        "waterfall_safety_status": "Viewing platforms safe, do not enter the water",
        "swimming_warning": False,
        "description": "Urban forest with walking paths, a waterfall, and historical caves.",
        "image_url": "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=1200&q=80",
        "duration_hours": 2.0,
        "gear_needed": ["Comfortable sneakers", "Water (1L)", "Light jacket", "Sunscreen"],
        "best_season": "Year-round",
        "guide_required": False,
        "starting_point": "Limuru Road Gate A",
        "permit_required": True,
        "fitness_level": "beginner"
    },
    {
        "name": "Hell's Gate",
        "difficulty": "easy",
        "distance_km": 21.0,
        "elevation_m": 1880,
        "location": "Nakuru County, near Naivasha",
        "waterfall_safety_status": "High flash flood risk in gorges, never enter without a certified guide",
        "swimming_warning": False,
        "description": "Hiking and cycling among cliffs, geothermal steam vents, and gorges.",
        "image_url": "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&q=80",
        "duration_hours": 4.0,
        "gear_needed": ["Sturdy shoes", "Sunglasses", "Sunscreen", "Water (2L)", "Bicycle (optional)"],
        "best_season": "June to October, January to March",
        "guide_required": False,
        "starting_point": "Elsa Gate",
        "permit_required": True,
        "fitness_level": "beginner"
    },
    {
        "name": "Aberdare Ranges",
        "difficulty": "hard",
        "distance_km": 15.0,
        "elevation_m": 3999,
        "location": "Nyandarua/Nyeri County",
        "waterfall_safety_status": "Karuru and Chania falls, stay behind protective railings",
        "swimming_warning": True,
        "description": "High-altitude moorland range with rainforests, waterfalls, and wildlife.",
        "image_url": "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1200&q=80",
        "duration_hours": 6.5,
        "gear_needed": ["Waterproof boots", "Warm fleece", "Rain jacket", "Water (2L)", "Lunch box"],
        "best_season": "January to March, July to September",
        "guide_required": True,
        "starting_point": "Mutubio Gate",
        "permit_required": True,
        "fitness_level": "advanced"
    },
    {
        "name": "Mount Suswa",
        "difficulty": "moderate",
        "distance_km": 11.0,
        "elevation_m": 2356,
        "location": "Narok County",
        "waterfall_safety_status": "Volcanic caves, dry area, no waterfalls",
        "swimming_warning": False,
        "description": "Double-crater volcanic mountain with an inner crater forest and obsidian caves.",
        "image_url": "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=1200&q=80",
        "duration_hours": 5.5,
        "gear_needed": ["Headlamp/torch", "Dust mask", "Sturdy boots", "Water (3L)", "Sun protection"],
        "best_season": "January to March, July to October",
        "guide_required": True,
        "starting_point": "Mount Suswa Conservancy Gate",
        "permit_required": True,
        "fitness_level": "intermediate"
    },
    # --- 12 new trails ---
    {
        "name": "Mount Satima (Dragon's Teeth)",
        "difficulty": "hard",
        "distance_km": 22.0,
        "elevation_m": 4001,
        "location": "Aberdare National Park, Shamata Gate",
        "waterfall_safety_status": "No major waterfalls, moorland stream crossings only",
        "swimming_warning": False,
        "description": "Highest peak in the Aberdares, with jagged rock formations known as the Dragon's Teeth.",
        "image_url": "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=80",
        "duration_hours": 8.0,
        "gear_needed": ["Warm thermal layers", "Rain pants", "Trekking boots", "High-energy snacks", "Water (3L)"],
        "best_season": "December to March, June to September",
        "guide_required": True,
        "starting_point": "Shamata Gate",
        "permit_required": True,
        "fitness_level": "advanced"
    },
    {
        "name": "Elephant Hill",
        "difficulty": "hard",
        "distance_km": 16.0,
        "elevation_m": 3906,
        "location": "Aberdare National Park",
        "waterfall_safety_status": "No waterfalls directly on trail",
        "swimming_warning": False,
        "description": "Challenging bamboo-forest-to-moorland trek, popular for Mt. Kenya/Kilimanjaro training.",
        "image_url": "https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?w=1200&q=80",
        "duration_hours": 8.0,
        "gear_needed": ["Sturdy hiking boots", "Raincoat", "Warm fleece", "Hiking poles", "Water (3L)"],
        "best_season": "December to March, June to September",
        "guide_required": True,
        "starting_point": "Njabini Forest Station",
        "permit_required": True,
        "fitness_level": "advanced"
    },
    {
        "name": "Table Mountain",
        "difficulty": "hard",
        "distance_km": 14.0,
        "elevation_m": 3906,
        "location": "Kwa Matu, Kipipiri, via Miharati town",
        "waterfall_safety_status": "No significant waterfalls",
        "swimming_warning": False,
        "description": "Sharp ascents through forest paths and moorland to a summit above the clouds.",
        "image_url": "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1200&q=80",
        "duration_hours": 7.0,
        "gear_needed": ["Waterproof hiking boots", "Warm fleece", "Water (2L)", "Snacks", "Windbreaker"],
        "best_season": "January to March, June to October",
        "guide_required": True,
        "starting_point": "Kwa Matu Kipipiri Forest Gate",
        "permit_required": True,
        "fitness_level": "advanced"
    },
    {
        "name": "Chyulu Hills",
        "difficulty": "moderate",
        "distance_km": 15.0,
        "elevation_m": 2188,
        "location": "Between Amboseli and Tsavo West National Parks",
        "waterfall_safety_status": "No waterfalls, dry volcanic terrain",
        "swimming_warning": False,
        "description": "Rolling volcanic hills with grasslands and the Leviathan lava tube cave system.",
        "image_url": "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=80",
        "duration_hours": 5.0,
        "gear_needed": ["Sturdy trail shoes", "Sun hat", "Water (3L)", "Insect repellent", "Sunscreen"],
        "best_season": "June to October",
        "guide_required": True,
        "starting_point": "KWS Chyulu Gate",
        "permit_required": True,
        "fitness_level": "intermediate"
    },
    {
        "name": "Menengai Crater",
        "difficulty": "moderate",
        "distance_km": 8.0,
        "elevation_m": 2278,
        "location": "Nakuru County",
        "waterfall_safety_status": "No waterfalls, dry crater rim",
        "swimming_warning": False,
        "description": "One of Kenya's most accessible crater hikes, close to Nairobi and Nakuru.",
        "image_url": "https://images.unsplash.com/photo-1418065460487-3e41a6c84dc5?w=1200&q=80",
        "duration_hours": 3.5,
        "gear_needed": ["Sports shoes", "Sunglasses", "Water (2L)", "Snacks", "Sun hat"],
        "best_season": "Year-round, best in dry months",
        "guide_required": False,
        "starting_point": "Menengai Crater Forest Gate",
        "permit_required": True,
        "fitness_level": "beginner"
    },
    {
        "name": "Mount Elgon",
        "difficulty": "hard",
        "distance_km": 20.0,
        "elevation_m": 4321,
        "location": "Bungoma County, Western Kenya",
        "waterfall_safety_status": "Waterfalls and river crossings present, check conditions with rangers",
        "swimming_warning": True,
        "description": "Extinct volcano on the Kenya-Uganda border with caves and multi-day trekking routes.",
        "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&q=80",
        "duration_hours": 18.0,
        "gear_needed": ["Thermal layers", "Camping gear", "Rain jacket", "Sturdy boots", "Water purification"],
        "best_season": "December to March",
        "guide_required": True,
        "starting_point": "Chorlim Gate",
        "permit_required": True,
        "fitness_level": "advanced"
    },
    {
        "name": "Ol Donyo Sabuk",
        "difficulty": "moderate",
        "distance_km": 10.0,
        "elevation_m": 2145,
        "location": "Machakos County, near Thika",
        "waterfall_safety_status": "No waterfalls on trail",
        "swimming_warning": False,
        "description": "Forested peak overlooking the Athi Plains, home to buffalo herds.",
        "image_url": "https://images.unsplash.com/photo-1536431311719-398b6704d4cc?w=1200&q=80",
        "duration_hours": 4.0,
        "gear_needed": ["Comfortable walking shoes", "Sunscreen", "Water (2L)", "Camera", "Light jacket"],
        "best_season": "Year-round",
        "guide_required": False,
        "starting_point": "Ol Donyo Sabuk National Park Gate",
        "permit_required": True,
        "fitness_level": "intermediate"
    },
    {
        "name": "Kinangop Peak",
        "difficulty": "hard",
        "distance_km": 18.0,
        "elevation_m": 3906,
        "location": "Aberdare National Park",
        "waterfall_safety_status": "No major waterfalls, moorland streams",
        "swimming_warning": False,
        "description": "One of the Aberdares' highest points, visible from Elephant Hill and Table Mountain.",
        "image_url": "https://images.unsplash.com/photo-1549880338-65ddcdfd017b?w=1200&q=80",
        "duration_hours": 9.0,
        "gear_needed": ["Trekking boots", "Warm waterproof layers", "Hiking poles", "High-energy snacks", "Water (3L)"],
        "best_season": "January to March, July to October",
        "guide_required": True,
        "starting_point": "Njabini Forest Station",
        "permit_required": True,
        "fitness_level": "advanced"
    },
    {
        "name": "Mount Kenya - Sirimon Route",
        "difficulty": "hard",
        "distance_km": 49.7,
        "elevation_m": 4985,
        "location": "Laikipia/Meru side, Mount Kenya National Park",
        "waterfall_safety_status": "River crossings, check levels in rainy season",
        "swimming_warning": False,
        "description": "The longest and highest-elevation-gain trail in Kenya, a multi-day summit route.",
        "image_url": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80",
        "duration_hours": 30.0,
        "gear_needed": ["Fleece and thermals", "Rain jacket & pants", "Warm gloves/beanie", "Sleeping bag", "Hiking poles"],
        "best_season": "December to March, July to September",
        "guide_required": True,
        "starting_point": "Sirimon Gate",
        "permit_required": True,
        "fitness_level": "advanced"
    },
    {
        "name": "Mount Kenya - Naro Moru Route",
        "difficulty": "hard",
        "distance_km": 44.0,
        "elevation_m": 4985,
        "location": "Nyeri side, Mount Kenya National Park",
        "waterfall_safety_status": "River crossings and the notorious vertical bog, use caution",
        "swimming_warning": False,
        "description": "The most popular summit route, known for its steep vertical bog section.",
        "image_url": "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=1200&q=80",
        "duration_hours": 28.0,
        "gear_needed": ["High waterproof boots", "Gaiters", "Warm sleepwear", "Thermal layers", "Rainwear"],
        "best_season": "December to March, July to September",
        "guide_required": True,
        "starting_point": "Naro Moru Gate",
        "permit_required": True,
        "fitness_level": "advanced"
    },
    {
        "name": "Ol Njorowa Gorge",
        "difficulty": "moderate",
        "distance_km": 24.0,
        "elevation_m": 1913,
        "location": "Hell's Gate National Park, Nakuru County",
        "waterfall_safety_status": "Geothermal hot springs in gorge, flash flood risk in rain, guide recommended",
        "swimming_warning": False,
        "description": "A narrow gorge walk fed by hot water springs, popular with cyclists and hikers.",
        "image_url": "https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=1200&q=80",
        "duration_hours": 5.5,
        "gear_needed": ["Shoes with good grip", "Water (2L)", "Snacks", "Dry bag for electronics", "Rain poncho"],
        "best_season": "January to March, July to October",
        "guide_required": True,
        "starting_point": "Hell's Gate Gorge Entrance",
        "permit_required": True,
        "fitness_level": "intermediate"
    },
    {
        "name": "Kakamega Forest",
        "difficulty": "easy",
        "distance_km": 7.0,
        "elevation_m": 1650,
        "location": "Kakamega County, Western Kenya",
        "waterfall_safety_status": "No significant waterfalls",
        "swimming_warning": False,
        "description": "Kenya's only tropical rainforest, known for birdwatching and canopy walks.",
        "image_url": "https://images.unsplash.com/photo-1511497584788-876760111969?w=1200&q=80",
        "duration_hours": 3.0,
        "gear_needed": ["Raincoat", "Insect repellent", "Walking shoes", "Binoculars", "Water (1L)"],
        "best_season": "December to March",
        "guide_required": False,
        "starting_point": "Isecheno Forest Station",
        "permit_required": True,
        "fitness_level": "beginner"
    }
]

def seed():
    print(f"Connecting to MongoDB at: {MONGO_URI}")
    client = MongoClient(MONGO_URI)
    db = client[MONGO_DB_NAME]
    
    print("Dropping existing 'trails' collection...")
    db.trails.drop()
    
    print(f"Seeding {len(trails_data)} trails...")
    result = db.trails.insert_many(trails_data)
    print("Successfully seeded!")
    print(f"Inserted IDs: {result.inserted_ids}")

if __name__ == '__main__':
    seed()
